# Generated by Django 3.1.2 on 2020-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsd_app', '0002_auto_20201013_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='addresscode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
